# Generated by Django 5.0.6 on 2024-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('B', 'Buyer'), ('S', 'Supplier')], default='B', max_length=1)),
                ('message_field', models.TextField()),
            ],
        ),
    ]
